yml update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -119,7 +119,7 @@ jobs:
                   then
                     echo "No source-backed components present in the package."
                     echo "So, Unable to start Validation"
-                    exit 1
+                    exit 1 | true
                   fi
                   sfdx force:source:deploy --manifest package/package.xml --targetusername ${{ secrets.USERNAME }} --checkonly --wait 0
             - name: Deployment of Code
@@ -128,7 +128,7 @@ jobs:
                 if [ -s package/package.xml ]
                 then
                   echo "No source-backed components present in the package."
-                  echo "So, Unable to start Validation"
-                  exit 1
+                  echo "So, Unable to start Deployment"
+                  exit 1 | true
                 fi
                 sfdx force:source:deploy --manifest package/package.xml --targetusername ${{ secrets.USERNAME }}
